sudo: required
services:
  - docker

language: generic
before_install:
  - docker build -t tamsnagy/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true tamsnagy/docker-react npm run test